package com.lm.hospital.model;

public enum LMNotificationType {
    APPOINTMENT_BOOKED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_REMINDER,
    GENERAL,
    MEDICAL_RECORD_UPDATE,
    BILLING_UPDATE
} 
